### ISSUE TITLE
Exe software for windows 10 64bit

### ISSUE THREAD

**Issue by nokiandrea** [Schallbert/DFplayer_AutoStructureFromPlaylist#3]
Hi, i want try your application, can you send me please executable version of your program?
thx,
Andrea
my mail is: nokiandroid84@gmail.com

**Comment by nokiandrea** [comment]
Thx for executable program but it don't work properly or i don't say use it.
At first boot has created a PlayListM3U folder.
I put in PlayListM3U my songs with extension .mp3 (example: title.mp3, secondtitle.mp3 and thirdtitle.mp3,ecc.), i run program and i find a new folder SDcardFolders with a subfolder 01 (folder 01 is empity). In PlayListM3U folder i find only my first file renominated in "01 title.mp3" .

**Comment by Schallbert** [comment]
OK, here is how it should work:
1.	Run the script once. It should create a „PlayListsM3U“ folder
2.	Open any mp3 player app of your choice, I use VLC player
3.	Pull the files you want to have in one folder of the SD card into the player’s main window.
 
4.	Sort the list to your wishes
5.	Save the playlist as an .m3u file.
 
6.	Repeat for any folder you want on your SD card
7.	Place the playlist files in the „PlayListsM3U“ folder
8.	Run the script again.

**Comment by Schallbert** [comment]
I will add a check for the right file type in the PlayListsM3U folder to give users another hint if they put the .mp3 files in this folder by mistake.

**Comment by Schallbert** [comment]
OK, I now have updated the script accordingly. Manual integration tests look fine. Added the .exe to this repo for quick download (works for Win10 x64 ONLY!) 
@nokiandrea please re-download .exe and feedback if it now works for you as well.

**Comment by Schallbert** [comment]
Closed due to missing feedback.
