### ISSUE TITLE
Suggestion: add .exe as Release Asset

### ISSUE THREAD

**Issue by ZengineerIO** [Schallbert/DFplayer_AutoStructureFromPlaylist#5]
as the title suggests 😘

**Comment by Schallbert** [comment]
The `.exe `is online on top level. Would you expect it under `/dist` or similar? Or do you suggest to setup a CD action?

**Comment by ZengineerIO** [comment]
Neither of those. I would suggest to remove the binary from the **source code** and create a release and a version tag and add the binary as asset to that release. You can then always create a new release with a new binary attached. This can be done easy with and without automation. 

Let me know if you need help or got questions.

Also sorry for the late reply here and best regards 😃

**Comment by Schallbert** [comment]
Ok, thanks for the tip; it was not hard to do at all - you just have to know how ^^
Assuming this is what you suggested I'll close this issue now.
